### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by samurairai** [jnsw/bt2bp#2]
HI Jan,

Can you pls share how do you connect the Wemos to the hoverboard?  I tried many pins but cant anything out from my Arduino Mega.  

Thanks in advance.

**Comment by jnsw** [comment]
It's under [Wiring](https://github.com/jnsw/bt2bp#wiring). The hoverboard pins are from the left sensor board (see picture below). 

What exactly is the problem? Define the pins from the Arduino in the code yourself, but my code shouldn't work with your setup, because it doesn't have bluetooth, does it?

Also don't forget to flash the Hoverboard **FIRST**!
For controlling the bipropellant-firmware see https://github.com/bipropellant/bipropellant-hoverboard-api

**Comment by samurairai** [comment]
Hi Jan,

I've compiled  bipropellant/bipropellant-hoverboard-firmware with
#define CONTROL_TYPE USART2_CONTROLLED

The firmware process are working as it worked well with TEST_MODE.

I've connected my Arduino Mega as below,

Arduino Mega Hoverboard
TX1 (pin 18) --- PA3 - UART3 RX
RX1 (pin 19) --- PA2 - UART2 TX

I used this sample code but still cannot see any data from the hoverboard.
https://github.com/bipropellant/bipropellant-hoverboard-api/tree/master/examples/PWMsimple

**Comment by jnsw** [comment]
I think there is no feedback of the hoverboard, I didn't used that, so I don't know, I just saw the wheels turning and it was everything I needed. Or maybe try different pins or check the pinout of the arduino, maybe the numbers are different.

**Comment by samurairai** [comment]
Hi Jan,

I've managed to get it to work with Arduino using codes from https://github.com/Combinacijus/hoverboard-firmware-hack.

Thanks.

**Comment by jnsw** [comment]
Your welcome!
