### ISSUE TITLE
Mobile app link broken

### ISSUE THREAD

**Issue by sebastienvg** [jnsw/bt2bp#3]
@jnsw I have a board sporting bipropellant firmware and an ESP32 flashed with your code. I search the playstore for an App called "Arduino Bluetooth Joystick" and found onen with "Unicia Robotics" logo at the bottom. When I try the D-pda the behaviour is at best erratic and at worst unexpected. The wheels aren't turning together or it's jerkin off and I think it's related to the android app settings. Can you share how you have yours setup?

**Comment by jnsw** [comment]
You can't use any Arduino Bluetooth Joystick, it needs to be the app I mentioned in the description. [Here](https://play.google.com/store/apps/details?id=com.juan.arducontrol)

**Comment by sebastienvg** [comment]
The link you provide is not working 
![image](https://user-images.githubusercontent.com/643465/102421353-44823c80-3fd2-11eb-911d-3f09807e4e03.png)

**Comment by sebastienvg** [comment]
For anyone trying to get this working the app is called ArduControl and I was able to get it from https://www.apkmonk.com/download-app/com.juan.arducontrol/4_com.juan.arducontrol_2019-04-07.apk/

**Comment by jnsw** [comment]
seems like the developer discontinued his project - so this repo need a rewrite for another joystick app to work with

sorry, the link i shared worked for me maybe because I have it in my play store library - i am sorry, here is an alternative url: https://apkpure.com/arduino-bluetooth-joystick/com.juan.arducontrol
